---
- name: Invoke gather function
  ansible.builtin.include_role:
    name: network.base.resource_manager
  vars:
    action: 'gather'
    resources:
      - 'bgp_global'
      - 'bgp_address_family'
